### ISSUE TITLE
Overlapping title with hero img

### ISSUE THREAD

**Issue by Hopelezz** [paabloLC/astro-neumorphismt#19]
![Screenshot_20220826-165304_Chrome.jpg](https://user-images.githubusercontent.com/72772558/186995736-37b7eaca-ae33-4058-86fd-835b77656529.jpg)

Also, it's neumorphism. You keep adding a `t` to the end.

**Comment by paabloLC** [comment]
@Hopelezz I just fixed the typo error in the card and in the header. Could you tell me which mobile are you using to take the screenshot??

Thank you!

**Comment by Hopelezz** [comment]
Samsung s21+

**Comment by paabloLC** [comment]
This is fixed, the issue can be closed, thx again for reporting.
