### ISSUE TITLE
Hope to know about the license

### ISSUE THREAD

**Issue by tuoxiansp** [paabloLC/astro-neumorphismt#36]
Hi, I saw your template on Astro's website. It's so cool. Can I use your template for my business project? I'm not sure if it's okay to use it, it's not licensed.

**Comment by paabloLC** [comment]
Of course, you can use my template to build your business project. =)

Really appreciate it if I could get a GitHub star at
https://github.com/paabloLC/astro-neumorphism it would be great if you send
me the link when you're done. I'd love to see your website, it will look so
great, I'm sure!

Have a great weekend! =)
Pablo.
